export const MOCK_USER = {
  uid: 'mock_user_123',
  email: 'owner@lifeos.app',
  displayName: 'LifeOS Owner',
  photoURL: null,
};

export const MOCK_APP_DATA = {
  studySessions: [
    { id: 's1', subject: 'Machine Learning', duration: 3600, date: new Date().toISOString(), notes: 'Deep learning transformers' },
    { id: 's2', subject: 'Algorithms', duration: 2700, date: new Date(Date.now() - 86400000).toISOString(), notes: 'Dynamic programming' },
    { id: 's3', subject: 'System Design', duration: 4500, date: new Date(Date.now() - 172800000).toISOString(), notes: 'Distributed cache' },
    { id: 's4', subject: 'Database Internals', duration: 3000, date: new Date(Date.now() - 259200000).toISOString(), notes: 'LSM trees vs B-trees' },
  ],
  workoutPlans: [
    {
      day: 'Mon',
      type: 'PUSH',
      exercises: [
        { name: 'Bench Press', howTo: 'Keep elbows at 45 deg', rest: '90s', sets: [{ reps: 10, weight: 80, completed: true }, { reps: 8, weight: 85, completed: true }, { reps: 6, weight: 90, completed: false }] },
        { name: 'Incline Dumbbell Press', howTo: '30 degree incline', rest: '60s', sets: [{ reps: 12, weight: 26, completed: true }, { reps: 10, weight: 28, completed: false }] },
        { name: 'Overhead Press', howTo: 'Core tight', rest: '90s', sets: [{ reps: 8, weight: 50, completed: true }] },
        { name: 'Lateral Raises', howTo: 'Slight bend in elbow', rest: '45s', sets: [{ reps: 15, weight: 12, completed: true }, { reps: 15, weight: 12, completed: true }] },
        { name: 'Tricep Pushdowns', howTo: 'Full extension', rest: '45s', sets: [{ reps: 12, weight: 30, completed: true }] },
      ],
    },
    { day: 'Tue', type: 'PULL', exercises: [{ name: 'Deadlift', howTo: 'Hips down, chest up', rest: '120s', sets: [{ reps: 5, weight: 140, completed: true }] }] },
    { day: 'Wed', type: 'CORE', exercises: [{ name: 'Hanging Leg Raise', howTo: 'No swinging', rest: '60s', sets: [{ reps: 15, weight: 0, completed: true }] }] },
    { day: 'Thu', type: 'PUSH', exercises: [{ name: 'Dips', howTo: 'Chest forward', rest: '90s', sets: [{ reps: 12, weight: 20, completed: true }] }] },
    { day: 'Fri', type: 'PULL', exercises: [{ name: 'Barbell Rows', howTo: 'Torso at 45 deg', rest: '90s', sets: [{ reps: 10, weight: 75, completed: true }] }] },
    { day: 'Sat', type: 'SHOULDERS', exercises: [{ name: 'Facepulls', howTo: 'External rotation', rest: '45s', sets: [{ reps: 20, weight: 25, completed: true }] }] },
    { day: 'Sun', type: 'REST', exercises: [] },
  ],
  workoutLogs: [
    {
      id: 'w1',
      date: new Date().toISOString().split('T')[0],
      day: 'Mon',
      type: 'PUSH',
      notes: 'Great pump today',
      exercises: [
        { name: 'Bench Press', sets: [{ reps: 10, weight: 80, completed: true }, { reps: 8, weight: 85, completed: true }] },
        { name: 'Incline DB Press', sets: [{ reps: 12, weight: 26, completed: true }] },
      ],
    },
    {
      id: 'w2',
      date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
      day: 'Sun',
      type: 'REST',
      notes: 'Active recovery walk',
      exercises: [],
    },
    {
      id: 'w3',
      date: new Date(Date.now() - 172800000).toISOString().split('T')[0],
      day: 'Sat',
      type: 'SHOULDERS',
      notes: 'Shoulder stability focus',
      exercises: [{ name: 'Facepulls', sets: [{ reps: 20, weight: 25, completed: true }] }],
    },
  ],
  expenses: [
    { id: 'e1', title: 'Groceries', amount: 84.50, category: 'Food', date: new Date().toISOString() },
    { id: 'e2', title: 'Coffee & Snacks', amount: 12.00, category: 'Food', date: new Date().toISOString() },
    { id: 'e3', title: 'Gym Membership', amount: 65.00, category: 'Health', date: new Date(Date.now() - 86400000).toISOString() },
    { id: 'e4', title: 'Metro Card Pass', amount: 30.00, category: 'Transport', date: new Date(Date.now() - 172800000).toISOString() },
    { id: 'e5', title: 'Cloud Server hosting', amount: 24.00, category: 'Bills', date: new Date(Date.now() - 259200000).toISOString() },
    { id: 'e6', title: 'Textbooks & Books', amount: 45.00, category: 'Education', date: new Date(Date.now() - 345600000).toISOString() },
    { id: 'e7', title: 'Dinner with team', amount: 58.20, category: 'Social', date: new Date(Date.now() - 432000000).toISOString() },
  ],
  timetable: [
    { id: 't1', day: 'Mon', title: 'Algorithms Lecture', time: '09:00 - 10:30', location: 'Hall A' },
    { id: 't2', day: 'Mon', title: 'Operating Systems Lab', time: '11:00 - 13:00', location: 'Lab 3' },
    { id: 't3', day: 'Mon', title: 'Distributed Systems', time: '14:00 - 15:30', location: 'Room 204' },
    { id: 't4', day: 'Tue', title: 'Database Seminar', time: '10:00 - 12:00', location: 'Room 101' },
    { id: 't5', day: 'Wed', title: 'AI & Ethics', time: '13:00 - 14:30', location: 'Hall B' },
    { id: 't6', day: 'Thu', title: 'Network Security', time: '09:30 - 11:00', location: 'Room 305' },
    { id: 't7', day: 'Fri', title: 'Capstone Project', time: '14:00 - 17:00', location: 'Lab 1' },
  ],
  tasks: [
    { id: 'tk1', title: 'Submit OS Lab Report', completed: false, priority: 'high', dueDate: new Date().toISOString(), category: 'Academic' },
    { id: 'tk2', title: 'Prepare presentation slides', completed: false, priority: 'medium', dueDate: new Date().toISOString(), category: 'Academic' },
    { id: 'tk3', title: 'Buy protein powder', completed: true, priority: 'low', dueDate: new Date().toISOString(), category: 'Health' },
    { id: 'tk4', title: 'Pay electricity bill', completed: false, priority: 'high', dueDate: new Date(Date.now() + 86400000).toISOString(), category: 'Personal' },
    { id: 'tk5', title: 'Review pull requests', completed: true, priority: 'medium', dueDate: new Date().toISOString(), category: 'Work' },
    { id: 'tk6', title: 'Clean apartment desk', completed: false, priority: 'low', dueDate: new Date().toISOString(), category: 'Personal' },
    { id: 'tk7', title: 'Book dentist appointment', completed: false, priority: 'medium', dueDate: new Date(Date.now() + 172800000).toISOString(), category: 'Health' },
    { id: 'tk8', title: 'Read Chapter 4 of DDIA', completed: false, priority: 'low', dueDate: new Date(Date.now() + 259200000).toISOString(), category: 'Study' },
    { id: 'tk9', title: 'Renew domain registrations', completed: false, priority: 'medium', dueDate: new Date(Date.now() + 345600000).toISOString(), category: 'Tech' },
    { id: 'tk10', title: 'Refactor mobile navigation hub', completed: true, priority: 'high', dueDate: new Date().toISOString(), category: 'Tech' },
    { id: 'tk11', title: 'Deep clean kitchen appliances', completed: false, priority: 'low', dueDate: new Date(Date.now() + 432000000).toISOString(), category: 'Personal' },
    { id: 'tk12', title: 'Update resume with project metrics', completed: false, priority: 'medium', dueDate: new Date(Date.now() + 518400000).toISOString(), category: 'Work' },
    { id: 'tk13', title: 'Order supplements refill', completed: false, priority: 'low', dueDate: new Date(Date.now() + 604800000).toISOString(), category: 'Health' },
    { id: 'tk14', title: 'Schedule mock technical interview', completed: false, priority: 'high', dueDate: new Date(Date.now() + 691200000).toISOString(), category: 'Academic' },
    { id: 'tk15', title: 'Audit weekly credit card receipts', completed: true, priority: 'medium', dueDate: new Date().toISOString(), category: 'Finance' },
  ],
  outings: [
    {
      id: 'out1',
      name: 'Weekend Mountain Trip',
      date: new Date().toISOString(),
      currency: 'USD',
      members: [
        { id: 'm1', name: 'Avineesh', isUser: true },
        { id: 'm2', name: 'Rohan', isUser: false },
        { id: 'm3', name: 'Sara', isUser: false },
      ],
      expenses: [
        { id: 'oe1', description: 'Cabin Rental', amount: 320, paidByMemberId: 'm1', splitBetweenMemberIds: ['m1', 'm2', 'm3'], date: new Date().toISOString() },
        { id: 'oe2', description: 'Groceries & BBQ', amount: 145, paidByMemberId: 'm2', splitBetweenMemberIds: ['m1', 'm2', 'm3'], date: new Date().toISOString() },
        { id: 'oe3', description: 'Gas & Tolls', amount: 65, paidByMemberId: 'm3', splitBetweenMemberIds: ['m1', 'm2', 'm3'], date: new Date().toISOString() },
      ],
    },
  ],
  reviews: [
    { id: 'rv1', date: new Date().toISOString().split('T')[0], rating: 4, text: 'Solid day of deep work and clean nutrition.', highlights: 'Finished Bench press sets' },
    { id: 'rv2', date: new Date(Date.now() - 86400000).toISOString().split('T')[0], rating: 5, text: 'Very productive study session.', highlights: 'Cracked DP problems' },
  ],
  settings: {
    theme: 'system',
    accentColor: '#6366F1',
    navPinned: ['gym', 'nutrition'],
    notificationLeadMinutes: 10,
  },
  profile: {
    name: 'LifeOS Owner',
    targetCalories: 2400,
    targetProtein: 160,
    targetWater: 3000,
  },
  menuMonths: [],
  nutritionLogs: [
    {
      id: 'nl1',
      date: new Date().toISOString().split('T')[0],
      meals: [
        { name: 'Oatmeal & Whey with Berries', calories: 520, protein: 42, carbs: 68, fats: 10, time: '08:30' },
        { name: 'Grilled Chicken Rice Bowl', calories: 750, protein: 58, carbs: 80, fats: 16, time: '13:00' },
        { name: 'Greek Yogurt & Almonds', calories: 280, protein: 24, carbs: 14, fats: 12, time: '17:00' },
        { name: 'Salmon with Sweet Potato & Veggies', calories: 680, protein: 48, carbs: 55, fats: 22, time: '20:30' },
      ],
      mealsEaten: [
        { slot: 'breakfast', mealId: 'breakfast', mealName: 'Breakfast', items: [{ id: 'i1', name: 'Oatmeal & Whey', calories: 520, portion: 1 }] },
        { slot: 'lunch', mealId: 'lunch', mealName: 'Lunch', items: [{ id: 'i2', name: 'Chicken Bowl', calories: 750, portion: 1 }] },
      ],
      dailyTotal: 2230,
      waterIntake: 2500,
    },
    {
      id: 'nl2',
      date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
      meals: [
        { name: 'Eggs, Toast & Avocado', calories: 580, protein: 32, carbs: 45, fats: 24, time: '09:00' },
        { name: 'Tuna Salad Wrap', calories: 610, protein: 45, carbs: 50, fats: 18, time: '13:30' },
        { name: 'Steak & Quinoa', calories: 820, protein: 62, carbs: 60, fats: 28, time: '20:00' },
      ],
      mealsEaten: [],
      dailyTotal: 2010,
      waterIntake: 2800,
    },
  ],
  messPreference: 'nonveg',
  geminiApiKey: '',
  vaultItems: [
    { id: 'v1', title: 'Apartment Lease Agreement', category: 'Documents', content: 'Lease active until Dec 2026', updatedAt: new Date().toISOString() },
    { id: 'v2', title: 'WiFi Network Recovery Keys', category: 'Passwords', content: 'Mesh-5G-Key: 99482710384', updatedAt: new Date().toISOString() },
    { id: 'v3', title: 'Passport Scan Reference', category: 'Identity', content: 'Doc ID: Z987654321', updatedAt: new Date().toISOString() },
  ],
  vaultConfig: {
    pinHash: '1234',
    biometricsEnabled: true,
  },
  laundryBatches: [
    {
      id: 'lb1',
      name: 'Weekly Wash - Darks & Gym',
      status: 'submitted',
      totalClothes: 8,
      submitDate: '2026-09-20',
      returnDate: '2026-09-23',
      createdAt: new Date().toISOString(),
      startedAt: new Date().toISOString(),
      items: [
        { category: 'Shirts', count: 3 },
        { category: 'Pants', count: 2 },
        { category: 'Socks', count: 3 },
      ],
    },
    {
      id: 'lb2',
      name: 'Bedding & Towels',
      status: 'received',
      totalClothes: 4,
      submitDate: '2026-09-18',
      returnDate: '2026-09-20',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      startedAt: new Date(Date.now() - 86400000).toISOString(),
      items: [
        { category: 'Towels', count: 2 },
        { category: 'Bed-sheets', count: 2 },
      ],
    },
  ],
  shoppingLists: [
    {
      id: 'sl1',
      name: 'Supermarket Run',
      color: '#6366F1',
      items: [
        { id: 'sli1', text: 'Rolled Oats 1kg', completed: true },
        { id: 'sli2', text: 'Chicken Breast 2kg', completed: false },
        { id: 'sli3', text: 'Eggs 30-pack', completed: true },
        { id: 'sli4', text: 'Greek Yogurt 1kg', completed: false },
        { id: 'sli5', text: 'Spinach & Brocolli', completed: false },
        { id: 'sli6', text: 'Peanut Butter crunchy', completed: false },
      ],
    },
  ],
};
